name = "moderateur-bedones"
compatibility_date = "2024-09-29"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "moderateur_bedones_db"
database_name = "moderateur-bedones-db"
database_id = "0d7ab73c-d8d6-443d-b3ac-cc3a7adb1028"
migrations_dir = "migrations"

[env.production]
name = "moderateur-bedones"

[env.production.vars]
NODE_ENV = "production"
FACEBOOK_APP_ID = "4075904832690760"
INSTAGRAM_APP_ID = "1336655694790025"

[[env.production.d1_databases]]
binding = "moderateur_bedones_db"
database_name = "moderateur-bedones-db"
database_id = "0d7ab73c-d8d6-443d-b3ac-cc3a7adb1028"

[env.preview]
name = "moderateur-bedones-preview"

[env.preview.vars]
NODE_ENV = "production"
FACEBOOK_APP_ID = "4075904832690760"
INSTAGRAM_APP_ID = "1336655694790025"

[[env.preview.d1_databases]]
binding = "moderateur_bedones_db"
database_name = "moderateur-bedones-db"
database_id = "0d7ab73c-d8d6-443d-b3ac-cc3a7adb1028"